# -*- coding: utf-8 -*-
"""Aula 2 - limpando e preparando dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srXiNB7rTm-4wH7nXbhC5cKuVstdqZ-7
"""

print('Vou aprender python para dados');
idade = 21;
nome = "William"
print("Meu nome é " , nome , " tenho " , idade , " anos");

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head(10)

df.info()

df.describe()

df.shape

df.isnull()

df.head()

df.isnull().sum()

df['ano_trabalho'].unique()

df[df.isnull().any(axis=1)]

"""preenchimento de dados

mean = media
median = mediana
"""

import numpy as np

# criando dataframe teste
df_salarios = pd.DataFrame({
    'nome' : ["William" , "Flavia" , "Cindy" , "Paulo" , "Joao"],
    'salario' : [4000 , np.nan , 5000 , np.nan , 100000]


})

# calcula as medias e substitui os nulos pela media e arredonda o valor
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))


'''
Calcula a mediana e substitui os nulos pela mediana
'''
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

df_temp = pd.DataFrame({
    'dia' : ['Segunda' , 'Terça', 'Quarta' , 'Quinta' , 'Sexta'],
    'temps' : [30 , np.nan , np.nan , 28 , 27]

})

df_temp['preenchido_ffill'] = df_temp['temps'].ffill()

df_temp

df_temp = pd.DataFrame({
    'dia' : ['Segunda' , 'Terça', 'Quarta' , 'Quinta' , 'Sexta'],
    'temps' : [30 , np.nan , np.nan , 28 , 27]

})

df_temp['preenchido_bfill'] = df_temp['temps'].bfill()

df_temp

df_cidades = pd.DataFrame({
        'nome' : ["William" , "Flavia" , "Cindy" , "Joao"],
        'cidades' : [ 'Guaarapuava' , 'Irati' , np.nan , 'Balneario Camboriu' ]

})

df_cidades['cidade_preenchida'] = df_cidades['cidades'].fillna('não informado')

df_cidades

"""excluindo"""

df_limpo = df.dropna()
df_limpo.isnull().sum()
df_limpo.head()

df_limpo.info()

df_limpo = df_limpo.assign(ano_trabalho = df_limpo['ano_trabalho'].astype('int64'))